/*
 Copyright (c) 2019 Kevin Jones, All rights reserved.
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
 3. The name of the author may not be used to endorse or promote products
    derived from this software without specific prior written permission.
 */

package com.nawforce.runforce.SObjects;

import com.nawforce.runforce.Internal.SObjectFields$;
import com.nawforce.runforce.Internal.SObjectType$;
import com.nawforce.runforce.System.*;

@SuppressWarnings("unused")
public class MutingPermissionSet extends SObject {
	public static SObjectType$<MutingPermissionSet> SObjectType;
	public static SObjectFields$<MutingPermissionSet> Fields;

	public Id CreatedById;
	public User CreatedBy;
	public Datetime CreatedDate;
	public com.nawforce.runforce.System.String DeveloperName;
	public Id Id;
	public com.nawforce.runforce.System.Boolean IsDeleted;
	public com.nawforce.runforce.System.String Language;
	public Id LastModifiedById;
	public User LastModifiedBy;
	public Datetime LastModifiedDate;
	public com.nawforce.runforce.System.String MasterLabel;
	public com.nawforce.runforce.System.Boolean PermissionsAICreateInsightObjects;
	public com.nawforce.runforce.System.Boolean PermissionsAIViewInsightObjects;
	public com.nawforce.runforce.System.Boolean PermissionsAccessCMC;
	public com.nawforce.runforce.System.Boolean PermissionsAccessContentBuilder;
	public com.nawforce.runforce.System.Boolean PermissionsAccountSwitcherUser;
	public com.nawforce.runforce.System.Boolean PermissionsActivateContract;
	public com.nawforce.runforce.System.Boolean PermissionsActivateOrder;
	public com.nawforce.runforce.System.Boolean PermissionsActivitiesAccess;
	public com.nawforce.runforce.System.Boolean PermissionsAddAnalyticsRemoteConnections;
	public com.nawforce.runforce.System.Boolean PermissionsAddDirectMessageMembers;
	public com.nawforce.runforce.System.Boolean PermissionsAddWaveNotificationRecipients;
	public com.nawforce.runforce.System.Boolean PermissionsAllowEmailIC;
	public com.nawforce.runforce.System.Boolean PermissionsAllowLightningLogin;
	public com.nawforce.runforce.System.Boolean PermissionsAllowUniversalSearch;
	public com.nawforce.runforce.System.Boolean PermissionsAllowViewEditConvertedLeads;
	public com.nawforce.runforce.System.Boolean PermissionsAllowViewKnowledge;
	public com.nawforce.runforce.System.Boolean PermissionsApexRestServices;
	public com.nawforce.runforce.System.Boolean PermissionsApiEnabled;
	public com.nawforce.runforce.System.Boolean PermissionsAssignPermissionSets;
	public com.nawforce.runforce.System.Boolean PermissionsAssignTopics;
	public com.nawforce.runforce.System.Boolean PermissionsAuthorApex;
	public com.nawforce.runforce.System.Boolean PermissionsAutomaticActivityCapture;
	public com.nawforce.runforce.System.Boolean PermissionsB2BMarketingAnalyticsUser;
	public com.nawforce.runforce.System.Boolean PermissionsBotManageBots;
	public com.nawforce.runforce.System.Boolean PermissionsBotManageBotsTrainingData;
	public com.nawforce.runforce.System.Boolean PermissionsBulkApiHardDelete;
	public com.nawforce.runforce.System.Boolean PermissionsBulkMacrosAllowed;
	public com.nawforce.runforce.System.Boolean PermissionsCampaignInfluence2;
	public com.nawforce.runforce.System.Boolean PermissionsCanApproveFeedPost;
	public com.nawforce.runforce.System.Boolean PermissionsCanEditDataPrepRecipe;
	public com.nawforce.runforce.System.Boolean PermissionsCanEditPrompts;
	public com.nawforce.runforce.System.Boolean PermissionsCanInsertFeedSystemFields;
	public com.nawforce.runforce.System.Boolean PermissionsCanManageMaps;
	public com.nawforce.runforce.System.Boolean PermissionsCanUseNewDashboardBuilder;
	public com.nawforce.runforce.System.Boolean PermissionsCanVerifyComment;
	public com.nawforce.runforce.System.Boolean PermissionsChangeDashboardColors;
	public com.nawforce.runforce.System.Boolean PermissionsChatterComposeUiCodesnippet;
	public com.nawforce.runforce.System.Boolean PermissionsChatterEditOwnPost;
	public com.nawforce.runforce.System.Boolean PermissionsChatterEditOwnRecordPost;
	public com.nawforce.runforce.System.Boolean PermissionsChatterFileLink;
	public com.nawforce.runforce.System.Boolean PermissionsChatterInternalUser;
	public com.nawforce.runforce.System.Boolean PermissionsChatterInviteExternalUsers;
	public com.nawforce.runforce.System.Boolean PermissionsChatterOwnGroups;
	public com.nawforce.runforce.System.Boolean PermissionsCloseConversations;
	public com.nawforce.runforce.System.Boolean PermissionsConfigCustomRecs;
	public com.nawforce.runforce.System.Boolean PermissionsConnectOrgToEnvironmentHub;
	public com.nawforce.runforce.System.Boolean PermissionsConsentApiUpdate;
	public com.nawforce.runforce.System.Boolean PermissionsContentAdministrator;
	public com.nawforce.runforce.System.Boolean PermissionsContentHubUser;
	public com.nawforce.runforce.System.Boolean PermissionsContentWorkspaces;
	public com.nawforce.runforce.System.Boolean PermissionsConvertLeads;
	public com.nawforce.runforce.System.Boolean PermissionsCreateCustomizeDashboards;
	public com.nawforce.runforce.System.Boolean PermissionsCreateCustomizeFilters;
	public com.nawforce.runforce.System.Boolean PermissionsCreateCustomizeReports;
	public com.nawforce.runforce.System.Boolean PermissionsCreateDashboardFolders;
	public com.nawforce.runforce.System.Boolean PermissionsCreateLtngTempFolder;
	public com.nawforce.runforce.System.Boolean PermissionsCreateLtngTempInPub;
	public com.nawforce.runforce.System.Boolean PermissionsCreatePackaging;
	public com.nawforce.runforce.System.Boolean PermissionsCreateReportFolders;
	public com.nawforce.runforce.System.Boolean PermissionsCreateReportInLightning;
	public com.nawforce.runforce.System.Boolean PermissionsCreateTopics;
	public com.nawforce.runforce.System.Boolean PermissionsCreateWorkBadgeDefinition;
	public com.nawforce.runforce.System.Boolean PermissionsCreateWorkspaces;
	public com.nawforce.runforce.System.Boolean PermissionsCustomMobileAppsAccess;
	public com.nawforce.runforce.System.Boolean PermissionsCustomSidebarOnAllPages;
	public com.nawforce.runforce.System.Boolean PermissionsCustomizeApplication;
	public com.nawforce.runforce.System.Boolean PermissionsDataExport;
	public com.nawforce.runforce.System.Boolean PermissionsDelegatedTwoFactor;
	public com.nawforce.runforce.System.Boolean PermissionsDeleteActivatedContract;
	public com.nawforce.runforce.System.Boolean PermissionsDeleteTopics;
	public com.nawforce.runforce.System.Boolean PermissionsDistributeFromPersWksp;
	public com.nawforce.runforce.System.Boolean PermissionsEditActivatedOrders;
	public com.nawforce.runforce.System.Boolean PermissionsEditBrandTemplates;
	public com.nawforce.runforce.System.Boolean PermissionsEditCaseComments;
	public com.nawforce.runforce.System.Boolean PermissionsEditEvent;
	public com.nawforce.runforce.System.Boolean PermissionsEditHtmlTemplates;
	public com.nawforce.runforce.System.Boolean PermissionsEditKnowledge;
	public com.nawforce.runforce.System.Boolean PermissionsEditMyDashboards;
	public com.nawforce.runforce.System.Boolean PermissionsEditMyReports;
	public com.nawforce.runforce.System.Boolean PermissionsEditOppLineItemUnitPrice;
	public com.nawforce.runforce.System.Boolean PermissionsEditPublicDocuments;
	public com.nawforce.runforce.System.Boolean PermissionsEditPublicFilters;
	public com.nawforce.runforce.System.Boolean PermissionsEditPublicTemplates;
	public com.nawforce.runforce.System.Boolean PermissionsEditReadonlyFields;
	public com.nawforce.runforce.System.Boolean PermissionsEditTask;
	public com.nawforce.runforce.System.Boolean PermissionsEditTopics;
	public com.nawforce.runforce.System.Boolean PermissionsEmailAdministration;
	public com.nawforce.runforce.System.Boolean PermissionsEmailMass;
	public com.nawforce.runforce.System.Boolean PermissionsEmailSingle;
	public com.nawforce.runforce.System.Boolean PermissionsEmailTemplateManagement;
	public com.nawforce.runforce.System.Boolean PermissionsEnableCommunityAppLauncher;
	public com.nawforce.runforce.System.Boolean PermissionsEnableNotifications;
	public com.nawforce.runforce.System.Boolean PermissionsExportReport;
	public com.nawforce.runforce.System.Boolean PermissionsFeedPinning;
	public com.nawforce.runforce.System.Boolean PermissionsFieldServiceAccess;
	public com.nawforce.runforce.System.Boolean PermissionsFieldServiceDispatcher;
	public com.nawforce.runforce.System.Boolean PermissionsFieldServiceLastMile;
	public com.nawforce.runforce.System.Boolean PermissionsFieldServiceMobileApp;
	public com.nawforce.runforce.System.Boolean PermissionsFieldServiceScheduling;
	public com.nawforce.runforce.System.Boolean PermissionsFlowUFLRequired;
	public com.nawforce.runforce.System.Boolean PermissionsForceTwoFactor;
	public com.nawforce.runforce.System.Boolean PermissionsGiveRecognitionBadge;
	public com.nawforce.runforce.System.Boolean PermissionsGovernNetworks;
	public com.nawforce.runforce.System.Boolean PermissionsHasUnlimitedNBAExecutions;
	public com.nawforce.runforce.System.Boolean PermissionsHeadlessCMSAccess;
	public com.nawforce.runforce.System.Boolean PermissionsHideReadByList;
	public com.nawforce.runforce.System.Boolean PermissionsIdentityConnect;
	public com.nawforce.runforce.System.Boolean PermissionsIdentityEnabled;
	public com.nawforce.runforce.System.Boolean PermissionsImportCustomObjects;
	public com.nawforce.runforce.System.Boolean PermissionsImportLeads;
	public com.nawforce.runforce.System.Boolean PermissionsImportPersonal;
	public com.nawforce.runforce.System.Boolean PermissionsInsightsAppAdmin;
	public com.nawforce.runforce.System.Boolean PermissionsInsightsAppDashboardEditor;
	public com.nawforce.runforce.System.Boolean PermissionsInsightsAppEltEditor;
	public com.nawforce.runforce.System.Boolean PermissionsInsightsAppUploadUser;
	public com.nawforce.runforce.System.Boolean PermissionsInsightsAppUser;
	public com.nawforce.runforce.System.Boolean PermissionsInsightsCreateApplication;
	public com.nawforce.runforce.System.Boolean PermissionsInstallPackaging;
	public com.nawforce.runforce.System.Boolean PermissionsIotUser;
	public com.nawforce.runforce.System.Boolean PermissionsIsotopeAccess;
	public com.nawforce.runforce.System.Boolean PermissionsIsotopeCToCUser;
	public com.nawforce.runforce.System.Boolean PermissionsIsotopeLEX;
	public com.nawforce.runforce.System.Boolean PermissionsLMEndMessagingSessionUserPerm;
	public com.nawforce.runforce.System.Boolean PermissionsLMOutboundMessagingUserPerm;
	public com.nawforce.runforce.System.Boolean PermissionsLearningManager;
	public com.nawforce.runforce.System.Boolean PermissionsLifecycleManagementAPIUser;
	public com.nawforce.runforce.System.Boolean PermissionsLightningConsoleAllowedForUser;
	public com.nawforce.runforce.System.Boolean PermissionsLightningExperienceUser;
	public com.nawforce.runforce.System.Boolean PermissionsListEmailSend;
	public com.nawforce.runforce.System.Boolean PermissionsLtngPromoReserved01UserPerm;
	public com.nawforce.runforce.System.Boolean PermissionsManageAnalyticSnapshots;
	public com.nawforce.runforce.System.Boolean PermissionsManageAuthProviders;
	public com.nawforce.runforce.System.Boolean PermissionsManageBusinessHourHolidays;
	public com.nawforce.runforce.System.Boolean PermissionsManageC360AConnections;
	public com.nawforce.runforce.System.Boolean PermissionsManageCMS;
	public com.nawforce.runforce.System.Boolean PermissionsManageCallCenters;
	public com.nawforce.runforce.System.Boolean PermissionsManageCases;
	public com.nawforce.runforce.System.Boolean PermissionsManageCategories;
	public com.nawforce.runforce.System.Boolean PermissionsManageCertificates;
	public com.nawforce.runforce.System.Boolean PermissionsManageChatterMessages;
	public com.nawforce.runforce.System.Boolean PermissionsManageContentPermissions;
	public com.nawforce.runforce.System.Boolean PermissionsManageContentProperties;
	public com.nawforce.runforce.System.Boolean PermissionsManageContentTypes;
	public com.nawforce.runforce.System.Boolean PermissionsManageCustomPermissions;
	public com.nawforce.runforce.System.Boolean PermissionsManageCustomReportTypes;
	public com.nawforce.runforce.System.Boolean PermissionsManageDashbdsInPubFolders;
	public com.nawforce.runforce.System.Boolean PermissionsManageDataCategories;
	public com.nawforce.runforce.System.Boolean PermissionsManageDataIntegrations;
	public com.nawforce.runforce.System.Boolean PermissionsManageDynamicDashboards;
	public com.nawforce.runforce.System.Boolean PermissionsManageEmailClientConfig;
	public com.nawforce.runforce.System.Boolean PermissionsManageEncryptionKeys;
	public com.nawforce.runforce.System.Boolean PermissionsManageExchangeConfig;
	public com.nawforce.runforce.System.Boolean PermissionsManageExternalConnections;
	public com.nawforce.runforce.System.Boolean PermissionsManageHealthCheck;
	public com.nawforce.runforce.System.Boolean PermissionsManageHubConnections;
	public com.nawforce.runforce.System.Boolean PermissionsManageInteraction;
	public com.nawforce.runforce.System.Boolean PermissionsManageInternalUsers;
	public com.nawforce.runforce.System.Boolean PermissionsManageIpAddresses;
	public com.nawforce.runforce.System.Boolean PermissionsManageKnowledge;
	public com.nawforce.runforce.System.Boolean PermissionsManageKnowledgeImportExport;
	public com.nawforce.runforce.System.Boolean PermissionsManageLeads;
	public com.nawforce.runforce.System.Boolean PermissionsManageLearningReporting;
	public com.nawforce.runforce.System.Boolean PermissionsManageLoginAccessPolicies;
	public com.nawforce.runforce.System.Boolean PermissionsManageMobile;
	public com.nawforce.runforce.System.Boolean PermissionsManageNetworks;
	public com.nawforce.runforce.System.Boolean PermissionsManagePasswordPolicies;
	public com.nawforce.runforce.System.Boolean PermissionsManageProfilesPermissionsets;
	public com.nawforce.runforce.System.Boolean PermissionsManagePropositions;
	public com.nawforce.runforce.System.Boolean PermissionsManagePvtRptsAndDashbds;
	public com.nawforce.runforce.System.Boolean PermissionsManageQuotas;
	public com.nawforce.runforce.System.Boolean PermissionsManageRecommendationStrategies;
	public com.nawforce.runforce.System.Boolean PermissionsManageReleaseUpdates;
	public com.nawforce.runforce.System.Boolean PermissionsManageRemoteAccess;
	public com.nawforce.runforce.System.Boolean PermissionsManageReportsInPubFolders;
	public com.nawforce.runforce.System.Boolean PermissionsManageRoles;
	public com.nawforce.runforce.System.Boolean PermissionsManageSearchPromotionRules;
	public com.nawforce.runforce.System.Boolean PermissionsManageSecurityCommandCenter;
	public com.nawforce.runforce.System.Boolean PermissionsManageSessionPermissionSets;
	public com.nawforce.runforce.System.Boolean PermissionsManageSharing;
	public com.nawforce.runforce.System.Boolean PermissionsManageSolutions;
	public com.nawforce.runforce.System.Boolean PermissionsManageSubscriptions;
	public com.nawforce.runforce.System.Boolean PermissionsManageSurveys;
	public com.nawforce.runforce.System.Boolean PermissionsManageSynonyms;
	public com.nawforce.runforce.System.Boolean PermissionsManageTemplatedApp;
	public com.nawforce.runforce.System.Boolean PermissionsManageTerritories;
	public com.nawforce.runforce.System.Boolean PermissionsManageTranslation;
	public com.nawforce.runforce.System.Boolean PermissionsManageTwoFactor;
	public com.nawforce.runforce.System.Boolean PermissionsManageUnlistedGroups;
	public com.nawforce.runforce.System.Boolean PermissionsManageUsers;
	public com.nawforce.runforce.System.Boolean PermissionsMassInlineEdit;
	public com.nawforce.runforce.System.Boolean PermissionsMergeTopics;
	public com.nawforce.runforce.System.Boolean PermissionsModerateChatter;
	public com.nawforce.runforce.System.Boolean PermissionsModerateNetworkUsers;
	public com.nawforce.runforce.System.Boolean PermissionsModifyAllData;
	public com.nawforce.runforce.System.Boolean PermissionsModifyDataClassification;
	public com.nawforce.runforce.System.Boolean PermissionsModifyMetadata;
	public com.nawforce.runforce.System.Boolean PermissionsNativeWebviewScrolling;
	public com.nawforce.runforce.System.Boolean PermissionsNewReportBuilder;
	public com.nawforce.runforce.System.Boolean PermissionsOmnichannelInventorySync;
	public com.nawforce.runforce.System.Boolean PermissionsOptOutGeoLocationTracking;
	public com.nawforce.runforce.System.Boolean PermissionsOverrideForecasts;
	public com.nawforce.runforce.System.Boolean PermissionsPackaging2;
	public com.nawforce.runforce.System.Boolean PermissionsPackaging2Delete;
	public com.nawforce.runforce.System.Boolean PermissionsPackaging2PromoteVersion;
	public com.nawforce.runforce.System.Boolean PermissionsPasswordNeverExpires;
	public com.nawforce.runforce.System.Boolean PermissionsPaymentsAPIUser;
	public com.nawforce.runforce.System.Boolean PermissionsPreventClassicExperience;
	public com.nawforce.runforce.System.Boolean PermissionsPrivacyDataAccess;
	public com.nawforce.runforce.System.Boolean PermissionsPublishPackaging;
	public com.nawforce.runforce.System.Boolean PermissionsQueryAllFiles;
	public com.nawforce.runforce.System.Boolean PermissionsQuipMetricsAccess;
	public com.nawforce.runforce.System.Boolean PermissionsQuipUserEngagementMetrics;
	public com.nawforce.runforce.System.Boolean PermissionsRecordVisibilityAPI;
	public com.nawforce.runforce.System.Boolean PermissionsRemoveDirectMessageMembers;
	public com.nawforce.runforce.System.Boolean PermissionsResetPasswords;
	public com.nawforce.runforce.System.Boolean PermissionsRunFlow;
	public com.nawforce.runforce.System.Boolean PermissionsRunReports;
	public com.nawforce.runforce.System.Boolean PermissionsSalesAnalyticsUser;
	public com.nawforce.runforce.System.Boolean PermissionsSalesConsole;
	public com.nawforce.runforce.System.Boolean PermissionsSandboxTestingInCommunityApp;
	public com.nawforce.runforce.System.Boolean PermissionsScheduleReports;
	public com.nawforce.runforce.System.Boolean PermissionsSelectFilesFromSalesforce;
	public com.nawforce.runforce.System.Boolean PermissionsSendAnnouncementEmails;
	public com.nawforce.runforce.System.Boolean PermissionsSendCustomNotifications;
	public com.nawforce.runforce.System.Boolean PermissionsSendSitRequests;
	public com.nawforce.runforce.System.Boolean PermissionsServiceAnalyticsUser;
	public com.nawforce.runforce.System.Boolean PermissionsShareInternalArticles;
	public com.nawforce.runforce.System.Boolean PermissionsShowCompanyNameAsUserBadge;
	public com.nawforce.runforce.System.Boolean PermissionsSkipIdentityConfirmation;
	public com.nawforce.runforce.System.Boolean PermissionsSolutionImport;
	public com.nawforce.runforce.System.Boolean PermissionsStdAutomaticActivityCapture;
	public com.nawforce.runforce.System.Boolean PermissionsSubmitMacrosAllowed;
	public com.nawforce.runforce.System.Boolean PermissionsSubscribeDashboardRolesGrps;
	public com.nawforce.runforce.System.Boolean PermissionsSubscribeDashboardToOtherUsers;
	public com.nawforce.runforce.System.Boolean PermissionsSubscribeReportRolesGrps;
	public com.nawforce.runforce.System.Boolean PermissionsSubscribeReportToOtherUsers;
	public com.nawforce.runforce.System.Boolean PermissionsSubscribeReportsRunAsUser;
	public com.nawforce.runforce.System.Boolean PermissionsSubscribeToLightningDashboards;
	public com.nawforce.runforce.System.Boolean PermissionsSubscribeToLightningReports;
	public com.nawforce.runforce.System.Boolean PermissionsTraceXdsQueries;
	public com.nawforce.runforce.System.Boolean PermissionsTransactionalEmailSend;
	public com.nawforce.runforce.System.Boolean PermissionsTransferAnyCase;
	public com.nawforce.runforce.System.Boolean PermissionsTransferAnyEntity;
	public com.nawforce.runforce.System.Boolean PermissionsTransferAnyLead;
	public com.nawforce.runforce.System.Boolean PermissionsTwoFactorApi;
	public com.nawforce.runforce.System.Boolean PermissionsUseOmnichannelInventoryAPIs;
	public com.nawforce.runforce.System.Boolean PermissionsUseSubscriptionEmails;
	public com.nawforce.runforce.System.Boolean PermissionsUseTeamReassignWizards;
	public com.nawforce.runforce.System.Boolean PermissionsUseTemplatedApp;
	public com.nawforce.runforce.System.Boolean PermissionsUseWebLink;
	public com.nawforce.runforce.System.Boolean PermissionsViewAllActivities;
	public com.nawforce.runforce.System.Boolean PermissionsViewAllCustomSettings;
	public com.nawforce.runforce.System.Boolean PermissionsViewAllData;
	public com.nawforce.runforce.System.Boolean PermissionsViewAllForecasts;
	public com.nawforce.runforce.System.Boolean PermissionsViewAllForeignKeyNames;
	public com.nawforce.runforce.System.Boolean PermissionsViewAllProfiles;
	public com.nawforce.runforce.System.Boolean PermissionsViewAllUsers;
	public com.nawforce.runforce.System.Boolean PermissionsViewAnomalyEvents;
	public com.nawforce.runforce.System.Boolean PermissionsViewContent;
	public com.nawforce.runforce.System.Boolean PermissionsViewDataAssessment;
	public com.nawforce.runforce.System.Boolean PermissionsViewDataCategories;
	public com.nawforce.runforce.System.Boolean PermissionsViewDataLeakageEvents;
	public com.nawforce.runforce.System.Boolean PermissionsViewEncryptedData;
	public com.nawforce.runforce.System.Boolean PermissionsViewEventLogFiles;
	public com.nawforce.runforce.System.Boolean PermissionsViewHealthCheck;
	public com.nawforce.runforce.System.Boolean PermissionsViewHelpLink;
	public com.nawforce.runforce.System.Boolean PermissionsViewMyTeamsDashboards;
	public com.nawforce.runforce.System.Boolean PermissionsViewOnlyEmbeddedAppUser;
	public com.nawforce.runforce.System.Boolean PermissionsViewPlatformEvents;
	public com.nawforce.runforce.System.Boolean PermissionsViewPrivateStaticResources;
	public com.nawforce.runforce.System.Boolean PermissionsViewPublicDashboards;
	public com.nawforce.runforce.System.Boolean PermissionsViewPublicReports;
	public com.nawforce.runforce.System.Boolean PermissionsViewRoles;
	public com.nawforce.runforce.System.Boolean PermissionsViewSecurityCommandCenter;
	public com.nawforce.runforce.System.Boolean PermissionsViewSetup;
	public com.nawforce.runforce.System.Boolean PermissionsViewUserPII;
	public com.nawforce.runforce.System.Boolean PermissionsWaveManagePrivateAssetsUser;
	public com.nawforce.runforce.System.Boolean PermissionsWaveTabularDownload;
	public com.nawforce.runforce.System.Boolean PermissionsWorkCalibrationUser;
	public com.nawforce.runforce.System.Boolean PermissionsWorkDotComUserPerm;
	public Datetime SystemModstamp;

	public MutingPermissionSet clone$() {throw new java.lang.UnsupportedOperationException();}
	public MutingPermissionSet clone$(com.nawforce.runforce.System.Boolean preserveId) {throw new java.lang.UnsupportedOperationException();}
	public MutingPermissionSet clone$(com.nawforce.runforce.System.Boolean preserveId, com.nawforce.runforce.System.Boolean isDeepClone) {throw new java.lang.UnsupportedOperationException();}
	public MutingPermissionSet clone$(com.nawforce.runforce.System.Boolean preserveId, com.nawforce.runforce.System.Boolean isDeepClone, com.nawforce.runforce.System.Boolean preserveReadonlyTimestamps) {throw new java.lang.UnsupportedOperationException();}
	public MutingPermissionSet clone$(com.nawforce.runforce.System.Boolean preserveId, com.nawforce.runforce.System.Boolean isDeepClone, com.nawforce.runforce.System.Boolean preserveReadonlyTimestamps, com.nawforce.runforce.System.Boolean preserveAutonumber) {throw new java.lang.UnsupportedOperationException();}
}
