/*
 * Copyright (c) 2024 Certinia Inc. All rights reserved.
 */

package com.nawforce.runforce.SObjects;

import com.nawforce.runforce.Internal.SObjectFields$;
import com.nawforce.runforce.Internal.SObjectType$;
import com.nawforce.runforce.System.Boolean;
import com.nawforce.runforce.System.Integer;
import com.nawforce.runforce.System.String;
import com.nawforce.runforce.System.*;

@SuppressWarnings("unused")
public class VoucherDefinition extends SObject {
	public static SObjectType$<VoucherDefinition> SObjectType;
	public static SObjectFields$<VoucherDefinition> Fields;

	public Integer AutogeneratedCodeLength;
	public String CodePrefix;
	public String CodeSuffix;
	public Decimal CostPerVoucher;
	public Id CreatedById;
	public User CreatedBy;
	public Datetime CreatedDate;
	public String CurrencyIsoCode;
	public String Description;
	public Integer DiscountPercent;
	public Date EffectiveDate;
	public Datetime EffectiveDateTime;
	public Date ExpirationDate;
	public Datetime ExpirationDateTime;
	public Integer ExpirationPeriod;
	public String ExpirationPeriodUnit;
	public String ExpirationType;
	public Decimal FaceValue;
	public Boolean HasTimeBasedVoucherPeriod;
	public Id Id;
	public String ImageUrl;
	public Boolean IsActive;
	public Boolean IsDeleted;
	public Boolean IsPartialRedeemable;
	public Id LastModifiedById;
	public User LastModifiedBy;
	public Datetime LastModifiedDate;
	public Datetime LastReferencedDate;
	public Datetime LastViewedDate;
	public Id LoyaltyProgramId;
	public LoyaltyProgram LoyaltyProgram;
	public String Name;
	public Id OwnerId;
	public Name Owner;
	public Id PartnerAccountId;
	public Account PartnerAccount;
	public Id ProductCategoryDerivedFieldId;
	public ProductCategory ProductCategoryDerivedField;
	public Id ProductDerivedFieldId;
	public Product2 ProductDerivedField;
	public Id ProductId;
	public Name Product;
	public Datetime SystemModstamp;
	public String Type;

	public ApprovalSubmission[] ApprovalSubmissions;
	public ApprovalWorkItem[] ApprovalWorkItems;
	public AttachedContentDocument[] AttachedContentDocuments;
	public Attachment[] Attachments;
	public CombinedAttachment[] CombinedAttachments;
	public ContentDocumentLink[] ContentDocumentLinks;
	public FlowOrchestrationWorkItem[] FlowOrchestrationWorkItems;
	public VoucherDefinitionHistory[] Histories;
	public Note[] Notes;
	public NoteAndAttachment[] NotesAndAttachments;
	public ProcessInstance[] ProcessInstances;
	public ProcessInstanceHistory[] ProcessSteps;
	public GameReward[] RewardDefinitions;
	public VoucherDefinitionShare[] Shares;
	public Voucher[] VoucherVoucherDefinition;

	public VoucherDefinition clone$() {throw new java.lang.UnsupportedOperationException();}
	public VoucherDefinition clone$(Boolean preserveId) {throw new java.lang.UnsupportedOperationException();}
	public VoucherDefinition clone$(Boolean preserveId, Boolean isDeepClone) {throw new java.lang.UnsupportedOperationException();}
	public VoucherDefinition clone$(Boolean preserveId, Boolean isDeepClone, Boolean preserveReadonlyTimestamps) {throw new java.lang.UnsupportedOperationException();}
	public VoucherDefinition clone$(Boolean preserveId, Boolean isDeepClone, Boolean preserveReadonlyTimestamps, Boolean preserveAutonumber) {throw new java.lang.UnsupportedOperationException();}
}
